### ISSUE TITLE
Implement Google Sign-In

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#1]
**Is your feature request related to a problem? Please describe.**
Right now, the login buttons are non-functional. The user is taken to the next page without any verification or login process. Implement Google Sign-In for the app.

**Describe the solution you'd like**
Firebase can be used to implement the Sign-In process. On clicking the Google Sign In button, the person should be prompted to choose from his Gmail ids. He/She should be taken to the next page on successful login.

**Additional context**
Ensure that you do not hard code any strings in the app. All strings should be added to the strings.dart file. Follow the [contributing guidelines](https://github.com/CheshtaK/bookface/blob/master/.github/CONTRIBUTING.md).

**Comment by yash2189** [comment]
Hi I would like to contribute on this as a part of SCI-2020

**Comment by CheshtaK** [comment]
Hey @yash2189! Please join the Slack community channel provided in the Participant Selection Mail and wait for further instructions. The contribution period has not started yet. I'll assign you the issue when we start with the program.

**Comment by ishandeveloper** [comment]
### I can work on this!

@CheshtaK Can you please share the google-services.json file and add me as a Member in your Firebase Project?

**Comment by ishandeveloper** [comment]
@CheshtaK @himanshusharma89 Just linked a PR, can someone review it?

**Comment by himanshusharma89** [comment]
> @CheshtaK @himanshusharma89 Just linked a PR, can someone review it?

Wait, I'll check it
