### ISSUE TITLE
Add more book genres

### ISSUE THREAD

**Issue by abhinavsri360** [CheshtaK/bookface#11]
**Is your feature request related to a problem? Please describe.**
We must add more book genres, anyone doing so can refer to the link: https://www.oprahmag.com/entertainment/books/a29576863/types-of-book-genres/ and therefore, add more genres as per understanding, but in my opinion, I find these appropriate to be added.

**Describe the solution you'd like**
Genres to be added

**Additional context**
I would like to work on this feature.

**Comment by CheshtaK** [comment]
Sure @abhinavsri360! Go ahead. Assigning you.
