### ISSUE TITLE
google-services.json missing

### ISSUE THREAD

**Issue by abhinavsri360** [CheshtaK/bookface#22]
**Describe the bug**
google-services.json is missing and the application cannot be built if the file remains missing.

**To Reproduce**
Add the file google-services.json present on the firebase project module. Steps to reproduce the file are present on this blog on Stack-overflow.  Link: https://stackoverflow.com/questions/33866061/error-file-google-services-json-is-missing-from-module-root-folder-the-google

**Screenshots**
Here's the log which I get on running 'flutter run'
```yaml
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  ...\bookface\android\app\src\nullnull\google-services.json
  ...\bookface\android\app\src\debug\google-services.json
  ...\bookface\android\app\src\nullnullDebug\google-services.json
  ...\bookface\android\app\src\nullnull\debug\google-services.json
  ...\bookface\android\app\src\debug\nullnull\google-services.json
  ...\bookface\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 32s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by CheshtaK** [comment]
Hey @abhinavsri360! It's not a good idea to make the `google-services.json` file public. I'll send it to you on Slack.
