### ISSUE TITLE
Modify the Login Screen according to design guidelines

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#29]
**Is your feature request related to a problem? Please describe.**
Modify the Login design according to the guidelines present in DESIGN/mockups

**Describe the solution you'd like**
Implement the given design. It should be responsive to all screen sizes.

**Additional context**
Attach a screenshot of the new page or a working gif while creating a pull request.  Follow the [contributing guidelines](https://github.com/CheshtaK/bookface/blob/master/.github/CONTRIBUTING.md).

**Comment by ishandeveloper** [comment]
Can I work on this one @CheshtaK ?

**Comment by CheshtaK** [comment]
Sure @ishandeveloper! Go ahead.

**Comment by ishandeveloper** [comment]
Just linked a PR @himanshusharma89 @CheshtaK ?
