### ISSUE TITLE
Add icons in the Login Page 

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#3]
**Is your feature request related to a problem? Please describe.**
The login buttons are simply text buttons as of now. Add the Facebook and Google icons to their respective buttons.

**Describe the solution you'd like**
The icons should follow the style of the app. Do not modify the size of the buttons or the text.

**Additional context**
Ensure that you do not hard code any image locations in the app. All strings should be added to the images.dart file. Follow the [contributing guidelines](https://github.com/CheshtaK/bookface/blob/master/.github/CONTRIBUTING.md).

**Comment by yash2189** [comment]
Hi, I Would like to contribute on this as a part of SCI-2020

**Comment by CheshtaK** [comment]
Hey @yash2189! Please join the Slack community channel provided in the Participant Selection Mail and wait for further instructions. The contribution period has not started yet. I'll assign you the issue when we start with the program.
Do join the bookface channel and read the guidelines for participants. You can work on a single issue at a time.

**Comment by ishandeveloper** [comment]
@CheshtaK  I can work on this.

Please let me know, if you want me to add icons in the current buttons or, actually implement a google sign in and facebook sign in button based on their [Branding guidelines](https://developers.google.com/identity/branding-guidelines).

For example : 
<img width="256px" src="https://user-images.githubusercontent.com/54989142/85868401-d65d7980-b7e7-11ea-8341-f3d95579e3d8.png"/>
<img width="256px" src="https://user-images.githubusercontent.com/54989142/85868462-f42ade80-b7e7-11ea-8ea8-ff3922889393.png"/>

**Comment by CheshtaK** [comment]
According to the Branding Guidelines @ishandeveloper

**Comment by ishandeveloper** [comment]
@CheshtaK  Alright.

Can you assign the issue to me?

**Comment by CheshtaK** [comment]
Oh no. Sorry xD

**Comment by ishandeveloper** [comment]
Just linked a PR @CheshtaK  @himanshusharma89 .
