### ISSUE TITLE
Update README.md to add the License

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#37]
**Is your feature request related to a problem? Please describe.**
Currently the README does not mention the 'License' for ease of access to the contributors.

**Describe the solution you'd like**
Add a heading for the 'License' and link it to the existing GPL License. 

**Additional context**
Refer [template](https://github.com/othneildrew/Best-README-Template)

**Comment by yash2189** [comment]
Can I work on this issue?

**Comment by CheshtaK** [comment]
Let's close issue #38 first!

**Comment by yash2189** [comment]
Can I work on this now @CheshtaK since I have created a PR for #38

**Comment by CheshtaK** [comment]
Sure @yash2189! Go ahead

**Comment by yash2189** [comment]
Please review my PR #41 @CheshtaK
