### ISSUE TITLE
Add a 'Table of Contents' to the README.md

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#38]
**Is your feature request related to a problem? Please describe.**
With a lot of headings in the README, it is quite tedious to scroll down to explore a particular section.  

**Describe the solution you'd like**
Add a Table of Contents with appropriate links to corresponding sections.

**Additional context**
Refer [template](https://github.com/othneildrew/Best-README-Template)

**Comment by yash2189** [comment]
Can I work on this issue @CheshtaK ?

**Comment by CheshtaK** [comment]
Hey @yash2189! Sure go ahead.

**Comment by yash2189** [comment]
Please review my PR @CheshtaK

**Comment by CheshtaK** [comment]
Closed by #39
