### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#4]
**Is your feature request related to a problem? Please describe.**
The default Flutter icon is visible when the app is installed in the device. Create an appropriate icon for the app.

**Describe the solution you'd like**
Use the logo.png file available in the assets folder to create an icon visible on the app's installation.

**Additional context**
Attach a screenshot of the icon while creating a pull request.  Follow the [contributing guidelines](https://github.com/CheshtaK/bookface/blob/master/.github/CONTRIBUTING.md).

**Comment by Nishtha3512** [comment]
I want to work on this..please assign me this issue.

**Comment by CheshtaK** [comment]
Hey @Nishtha3512! Please join the Slack community channel provided in the Participant Selection Mail and wait for further instructions. The contribution period has not started yet. I'll assign you the issue when we start with the program.

**Comment by ishandeveloper** [comment]
### Can I work on this?

**Comment by ishandeveloper** [comment]
@CheshtaK @himanshusharma89 Just linked a PR, can someone review it?

**Comment by abhinavsri360** [comment]
How about this one? @CheshtaK @himanshusharma89 @ishandeveloper 
![image](https://user-images.githubusercontent.com/44001310/85296833-96348900-b4bf-11ea-990f-6450fe10ed02.png)

**Comment by CheshtaK** [comment]
Looks great @abhinavsri360 ! Open up an issue for this. Might get lost here :P

**Comment by abhinavsri360** [comment]
Ohh, I was just asking that if this was appropriate and get some reviews first 😅
