### ISSUE TITLE
Create a Navigation Drawer for the app

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#8]
**Is your feature request related to a problem? Please describe.**
Right now there is no option for the user to go to his profile or logout. Create a dummy home page (for now) and add a navigation drawer to it.

**Describe the solution you'd like**
The navigation drawer should necessarily contain these three drawer items - Home, My Profile and Logout. You can be creative and add more options as you see relevant.

**Additional context**
Make sure the drawer works for all screen sizes. Add all the strings in the constants/strings.dart file. Display relevant screenshots in the PR.

**Comment by abhinavsri360** [comment]
In the application, we are having a bottom fixed nav. I don't think there is a need for a nav drawer. Please let me know your views.

**Comment by CheshtaK** [comment]
Oh yes. That's my bad. Forgot I had implemented that. Thanks for pointing it out! Closing the issue.
