### ISSUE TITLE
Add network connectivity check

### ISSUE THREAD

**Issue by CheshtaK** [CheshtaK/bookface#9]
**Is your feature request related to a problem? Please describe.**
Presently there is no check to see if the user is connected to a network or not. Add a connectivity check before displaying the login page.

**Describe the solution you'd like**
When the user opens the app, if he/she is not connected to a network - display an appropriate toast. The toast should be displayed before the login screen (i.e on the splash screen). Without a connection the user should not be able to move forward to logging in.

**Additional context**
Add relevant screenshots. All strings should saved in the strings.dart file.

**Comment by ishandeveloper** [comment]
### I can work on this issue! 
Can someone assign this to me?

Also, please clarify, if the user needs to be connected to the network throughout the app, for example if the user logs in and then gets disconnected, should the app just remain functional or display an appropriate screen?

**Comment by CheshtaK** [comment]
@ishandeveloper Let's focus on adding a connectivity check before displaying the login page in this issue. You can open up a new issue to check network connectivity throughout the app. 

Assigning you the issue.

**Comment by ishandeveloper** [comment]
@CheshtaK , @himanshusharma89 I have linked a pull request for the above issue. Can someone review it?

**Comment by himanshusharma89** [comment]
> @CheshtaK , @himanshusharma89 I have linked a pull request for the above issue. Can someone review it?

Okay, wait.
